local svg_to_coords = require "svg_to_coords.svg_to_coords"

local coordinates
local position 

function init(self)
	
	position = go.get_position( "go" )
	coordinates = svg_to_coords:read( "/game/Path.svg" )

end

function update(self, dt)

	local count =  math.ceil(#coordinates/2)-2
	for i=0, count do

		local index = (i*2)+1
		local x1 = position.x + coordinates[index]
		local y1 = position.y + coordinates[index+1]
		local x2 = position.x + coordinates[index+2]
		local y2 = position.y + coordinates[index+3]

		msg.post("@render:", "draw_line", { start_point = vmath.vector3( x1,y1,0 ), end_point = vmath.vector3( x2,y2,0 ), color = vmath.vector4(1, 0, 0, 1) } )

	end

end

